alter table public.app_settings
  add column if not exists vapid_public_key text,
  add column if not exists vapid_private_key text,
  add column if not exists vapid_subject text default 'mailto:admin@campussense.local';

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity not null,
  user_id text not null default 'global-user',
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  is_active boolean not null default true,
  last_success_at timestamptz null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint push_subscriptions_pkey primary key (id),
  constraint push_subscriptions_endpoint_key unique (endpoint)
) tablespace pg_default;

create index if not exists idx_push_subscriptions_active
  on public.push_subscriptions using btree (is_active) tablespace pg_default;

create index if not exists idx_push_subscriptions_user
  on public.push_subscriptions using btree (user_id) tablespace pg_default;
