create table if not exists public.alert_thresholds (
  id bigint generated by default as identity not null,
  metric text not null,
  threshold_value numeric not null,
  alert_if_above boolean not null default true,
  description text null,
  updated_at timestamp with time zone null default now(),
  constraint alert_thresholds_pkey primary key (id),
  constraint alert_thresholds_metric_key unique (metric)
) tablespace pg_default;

create table if not exists public.app_settings (
  key text not null,
  threshold_aqi integer not null default 450,
  threshold_uv numeric(4, 1) not null default 7.0,
  threshold_bmp_temp numeric(5, 1) not null default 28.0,
  threshold_pressure integer not null default 990,
  threshold_rain_percentage integer not null default 70,
  report_times jsonb not null default '["09:00", "12:00", "18:00"]'::jsonb,
  alert_rate text not null default 'immediate'::text,
  timezone text not null default 'Asia/Kolkata'::text,
  updated_at timestamp with time zone not null default now(),
  constraint app_settings_pkey primary key (key)
) tablespace pg_default;

insert into public.app_settings (key)
values ('global')
on conflict (key) do nothing;

create table if not exists public.notifications (
  id bigint generated by default as identity not null,
  title text not null,
  message text not null,
  type text null default 'info'::text,
  is_read boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint notifications_pkey primary key (id)
) tablespace pg_default;

create index if not exists idx_notifications_created_at
  on public.notifications using btree (created_at desc) tablespace pg_default;

create index if not exists idx_notifications_read
  on public.notifications using btree (is_read) tablespace pg_default;

create table if not exists public.scheduled_reports (
  id bigint generated by default as identity not null,
  report_time text not null,
  is_active boolean null default true,
  last_sent_date date null,
  constraint scheduled_reports_pkey primary key (id)
) tablespace pg_default;

create table if not exists public.telegram_subscribers (
  id bigint generated by default as identity not null,
  chat_id bigint not null,
  first_name text null,
  username text null,
  is_subscribed boolean null default true,
  subscribed_at timestamp with time zone null default now(),
  constraint telegram_subscribers_pkey primary key (id),
  constraint telegram_subscribers_chat_id_key unique (chat_id)
) tablespace pg_default;
